// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCM.CAP.DeliveryService;

namespace TCM.CAP.DeliveryService.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TCM.CAP.DeliveryService.Delivery", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeliveryID");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("OrderID")
                        .HasColumnName("OrderID");

                    b.Property<string>("OrderUserID")
                        .HasColumnName("OrderUserID");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("UpdatedTime");

                    b.HasKey("ID");

                    b.ToTable("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
